### ISSUE TITLE
可以将评论发布栏移到评论区顶部吗

### ISSUE THREAD

**Issue by zhui-zi** [Skywt2003/Daydream#1]
对于已经有很多评论的文章还是有必要的，不然向下翻的话要很久~

**Comment by Skywt2003** [comment]
我有空就改 😵‍💫

**Comment by Skywt2003** [comment]
考虑了一下，个人还是觉得先展示评论再展示评论框比较协调 =_=
评论多的话以后可以做评论分页（不过现在还没遇到评论特别多的情况……）
如果有需要的话可以 Fork 自行更改
