### ISSUE TITLE
首页文章无法显示摘要，只能显示全文

### ISSUE THREAD

**Issue by Alankyleee** [Skywt2003/Daydream#4]
首页文章无法显示摘要，只能显示全文

**Comment by Skywt2003** [comment]
请在文章中插入 `<!--more-->` 标签。一篇文章中，`<!--more-->` 之前的部分会被视为摘要。也可以使用 Typecho 自带文章编辑器里的「摘要分隔线」按钮。

（这是 WordPress 和 Typecho 通行的做法）
